title: Charles Burns
description: meep moop
url: "https://charlesdgburns.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Navigation sections (used for automatic submenu generation)
sections:
  - name: about
    title: About
    path: ./about/
  - name: creating
    title: Creating
    path: ./creating/
  - name: learning
    title: Learning
    path: ./learning/
  - name: life
    title: Life
    path: ./life/
  

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock